services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_ENABLE_COMMUNITY_NODES=true
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
